services:
  frontend:
    build:
      context: ./app
      dockerfile: frontend.Dockerfile
    container_name: comix-web-frontend-frontend
    ports:
      - "4200:80"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: comix-web-frontend-api
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: comix-web-frontend-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
